name: Deploy to Production (on VPS)

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
           
      # Build
      - name: Pull latest changes on VPS
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.VPS_HOST }}
            USERNAME: ${{ secrets.VPS_DEPLOY_USER }}
            PORT: ${{ secrets.VPS_SSH_PORT }}
            KEY: ${{ secrets.VPS_SSHKEY }}
            script: cd ${{ secrets.VPS_PROJECT_PATH }} && git fetch && git pull
            
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.VPS_HOST }}
            USERNAME: ${{ secrets.VPS_DEPLOY_USER }}
            PORT: ${{ secrets.VPS_SSH_PORT }}
            KEY: ${{ secrets.VPS_SSHKEY }}
            script: cd ${{ secrets.VPS_PROJECT_PATH }} && make deploy-prod
